#!/usr/bin/env node

var path = require('path');
var commander = require('commander');

var gen_file = __dirname + '/generators/' + process.argv[2] + '.js';

path.exists(gen_file, function(exists) {
  if (exists) {
    var generator = require(gen_file);
    var options = commander.parseOptions();
    generator(options);
  }
  else {
    console.log("Unable to find generator '" + gen_file + "'");
  }
});
