#!/usr/bin/env node

var path = require('path');

var gen_file = __dirname+'/../generate/'+process.argv[2]+'.js';
console.log("GEN file:", gen_file);

path.exists(gen_file, function(exists) {
  if (exists) {
    var generator = require(gen_file);
    generator.apply(generator, process.argv);
  }
  else {
    console.log("Unable to find generator '" + gen_file + "'");
  }
});
